#Default world, the only world this pulgin can be used in (will be fixed in future update) set automatically at server start, 
# change if default world is not where this is being used
world:
mins:
  minx: 10
  miny: 2
  minz: 10
  
#The minimum number of players in lobby to start the match countdown

minplayers: 4


#The maximum number of players in a game

maxplayers: 20


#The length of time before a match start after the minimum number of players join, in seconds

matchcountdown: 120 #2 minutes


#Length of the first stage of the match where players collect resources, in seconds

firststagelength: 1800 #30 minutes


#Length of the second stage of the match where players fight, usually match will end first by
# players killing each other

secondstagelength: 900 #15 minutes


#Disable hunger damage and depletion in lobby and spectators?

hungerlobbydisable: true
hungerspectatordisable: true


#Friendly fire, i.e. red can damage red, blue can damage blue (false for no friendly fire)

friendlyfire: false


#Invicible in lobby and spectate?

invinciblelobby: false
invinciblespectators: false


#Disable damage types ONLY APPLIES TO PLAYERS IN THE ARENA I.E. RED OR BLUE TEAM

#Fall Damage
disablefall: true
#Hunger Damge, only damage, not depletion of hunger bar
disablehunger: false
#Drowning Damage
disabledrown: false
#Explosion Damage
disableexplosion: false
#Suffocation Damage
disablesuffocation: false
#Mob Damage (does not work on withers)
disablemobdamage: false 


#If the amount of players is not evenly divisible among the teams, should a player be sent to spectate, or should one team have an extra player?

extraplayerspectate: true


#Teleportation delay in seconds

teleportdelay: 4


#Payouts (REQUIRES VAULT)

#All members of the winning team recive
winpayout: 200
#Last player standing recives bouns (or multiple if from the same team, in addition to team win bonus)
lastmanbonus: 200
#All players on the losing team recive this, as a second place prize
losepayout: 0
#Last player alive on the losing team recives this
lastmanlose: 200


#Disallowed commands for players in the game (prevent tping out, etc.)

disallowedcommands: 
  - tp
  - tpa
  - tpahere
  - tphere
  - tppos
  - spawn
  - home
  - sethome
  - warp
  - setwarp
